# Copyright 2024 Gentoo Foundation
# Copyright 2024 Mike Frysinger <vapier@gentoo.org>
# Copyright 2024 The ChromiumOS Authors
# Distributed under the terms of the GNU General Public License v2

# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/


# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
[tool.black]
line-length = 88
target-version = ["py38"]


# https://pycqa.github.io/isort/docs/configuration/options
[tool.isort]
py_version = "38"

# Be compatible with `black` since it also matches what we want.
profile = "black"

line_length = 88
length_sort = false
force_single_line = true
lines_after_imports = 2
from_first = false
case_sensitive = false
force_sort_within_sections = true
order_by_type = false

# Allow importing multiple classes on a single line from these modules.
# https://google.github.io/styleguide/pyguide#s2.2-imports
single_line_exclusions = [
	"abc",
	"collections.abc",
	"typing",
]


# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
python_version = "3.8"
