# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://scan.coverity.com/projects/gentoo-pax-utils
name: Coverity Scan

on:
  push:
    branches: [master]

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vapier/coverity-scan-action@v1
      with:
        email: vapier@gentoo.org
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
