# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Python

on: [push, pull_request]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # NB: v1.4.0 covers Python 3.8.
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: lddtree.py pylint
        use-pylint: true
        use-pycodestyle: false
        use-flake8: false
        use-black: true
        use-mypy: true
        use-isort: true
        extra-pylint-options: ""
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""
